name: CI Simple Workflow

on:
  push:
    branches:
      - main

env:
  MY_VARIABLE: "This is a variable"

jobs: 
  say_hello_and_variable:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello, Github Actions!"

      - name: Display Environment Variable
        run: echo "The value of MY_VARIABLE is: $MY_VARIABLE"