name: CI Simple Workflow

on:
  push:
    branches: [ main ]

env:
  MY_VARIABLE: "This is a variable"

jobs:
  say_hello_and_secrets: 
    name: Say Hello, Display Variable and Display Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello, GitHub Actions !"

      - name: Display Environment Variable
        run: echo "The value of MY_VARIABLE is ${{ env.MY_VARIABLE }}"

      - name: Display Secret
        run: echo "Attempting to display MY_SECRET ${{ secrets.MY_SECRET }}"