name: CI Simple Workflow

on:
  push:
    branches: [ main ]

env:
  MY_VARIABLE: "This is a variable"

jobs:
  bash_script_job: 
    name: Run Bash Script
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello, GitHub Actions !"

      - name: Display Environment Variable
        run: echo "The value of MY_VARIABLE is ${{ env.MY_VARIABLE }}"

      - name: Display Secret
        run: echo "Attempting to display MY_SECRET ${{ secrets.MY_SECRET }}"

      - name: Create a file with Bash
        run: | 
          echo "Hello world" > hello.txt
          echo "File hello.txt created."

      - name: Display content of hello.txt
        run: cat hello.txt

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test